id: 9b5c283534494827bb6840cbbcde24d9
initial_creation_type: ocr
source_metadata:
  volumes:
    cc4f4ef2df314eadae61b09013d8ce3e:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: ''
      total_pages: 1853
      volume_number: 25
